apiVersion: v1
kind: Service
metadata:
  name: {{ include "opensnow.fullname" . }}-gateway
  labels:
    {{- include "opensnow.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.gateway.type }}
  {{- if and (eq .Values.gateway.type "LoadBalancer") .Values.gateway.loadBalancerIP }}
  loadBalancerIP: {{ .Values.gateway.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.gateway.type "LoadBalancer") .Values.gateway.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.gateway.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  selector:
    {{- include "opensnow.coordinator.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.gateway.port }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.gateway.type "NodePort") }}
      nodePort: 30080
      {{- end }}
    {{- if .Values.coordinator.pgwireEnabled }}
    - name: postgres
      port: {{ .Values.gateway.postgresPort }}
      targetPort: postgres
      protocol: TCP
      {{- if and (eq .Values.gateway.type "NodePort") }}
      nodePort: 30543
      {{- end }}
    {{- end }}
